### ISSUE TITLE
Crash when calling fbleau --version 

### ISSUE THREAD

**Issue by kadron** [gchers/fbleau#2]
I'm getting an error while calling this command.
```
$ fbleau --version 
thread 'main' panicked at '[!] failed to load training data: Error(Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }))', src/libcore/result.rs:997:5 note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by gchers** [comment]
Thank you for reporting this, and I'm sorry if I didn't see it before. It should now be fixed now, but feel free to re-open the ticket otherwise.

(Note that the argument `--version` is just for showing `fbleau`'s version. I'll package a new version of `fbleau` only for bigger changes, so this bug is not fixed in the version currently on https://crates.io.)
